# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/dmcclure/hello-server
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: go test -v ./...
      - run:
          name: "Build Docker image"
          command: docker build -t hello-server:$CIRCLE_BRANCH .

  deploy_to_development:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/dmcclure/hello-server
    steps:
      - run:
          name: "Deploy to development"
          command: echo TBD

  deploy_to_staging:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/dmcclure/hello-server
    steps:
      - run:
          name: "Deploy to staging"
          command: echo TBD

  deploy_to_production:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/dmcclure/hello-server
    steps:
      - run:
          name: "Deploy to production"
          command: echo TBD

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy_to_development:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy_to_staging:
          requires:
            - build
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
           - deploy_to_staging
      - deploy_to_production:
          requires:
            - hold
